
import com.lowagie.text.Document;
import com.lowagie.text.DocumentException;
import com.lowagie.text.pdf.PdfContentByte;
import com.lowagie.text.pdf.PdfCopy;
import com.lowagie.text.pdf.PdfImportedPage;
import com.lowagie.text.pdf.PdfReader;
import com.lowagie.text.pdf.PdfWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author itanortegaortega
 */
public class IuPpal extends javax.swing.JFrame {

    String origen = "/Users/itanortegaortega/Documents/pdf/Origen/";
    String tmp = "/Users/itanortegaortega/Documents/pdf/Tmp/";
    String salida = "/Users/itanortegaortega/Documents/pdf/Salida/";
    String archivo = "prueba.pdf";
    String hojaCompra = "hojaCompra.pdf";
    int nHojas = 1;
    /**
     * Creates new form IuPpal
     */
    public IuPpal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Btn_Proceder = new javax.swing.JButton();
        Spn_Hojas = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Btn_Proceder.setText("Proceder");
        Btn_Proceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ProcederActionPerformed(evt);
            }
        });

        Spn_Hojas.setModel(new javax.swing.SpinnerNumberModel(5, 1, 50, 1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(Spn_Hojas, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Btn_Proceder)
                .addContainerGap(129, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_Proceder)
                    .addComponent(Spn_Hojas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(299, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_ProcederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ProcederActionPerformed
        String sDirectorio = origen;
        File f = new File(sDirectorio);
        String nombre = "";
        String rutaArchivoOrigen = "";
        String rutaArchivoTmp = "";
        String rutaArchivoSalida = "";  
        String rutaArchivoHoja = ""; 
        nHojas = Integer.parseInt(Spn_Hojas.getValue().toString());
        
        File[] archivos = f.listFiles();
        for(int i=0; i<archivos.length; i++){
            nombre = archivos[i].getName();
            rutaArchivoOrigen = origen + nombre;
            rutaArchivoTmp = tmp + nombre;
            rutaArchivoSalida = salida + nombre;
            rutaArchivoHoja = origen + hojaCompra;
            
            if(!nombre.equals(".DS_Store") && !nombre.equals(hojaCompra)){
                System.out.println(rutaArchivoTmp);
                dividir(rutaArchivoOrigen, rutaArchivoTmp, nHojas);
                unirPdf(rutaArchivoTmp, rutaArchivoHoja, rutaArchivoSalida);
                System.out.println(rutaArchivoTmp + "__________________________");
            }
        }
        System.out.println("Listo!!!");
    }//GEN-LAST:event_Btn_ProcederActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IuPpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IuPpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IuPpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IuPpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IuPpal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Proceder;
    private javax.swing.JSpinner Spn_Hojas;
    // End of variables declaration//GEN-END:variables

    private void dividir(String origen, String destino, int nPaginas) {
        try {
            PdfReader reader = new PdfReader(origen);
            int n = reader.getNumberOfPages();
            if(n < nPaginas){
                nPaginas = n;
            }
            Document document = new Document();
            PdfCopy pdfCopy = new PdfCopy(document, new FileOutputStream(destino));
            document.open();
            for(int i = 1; i<= nPaginas; i++){
                pdfCopy.addPage(pdfCopy.getImportedPage(reader, i));
            }            
            document.close();
        } catch (IOException ex) {
            Logger.getLogger(IuPpal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DocumentException ex) {
            Logger.getLogger(IuPpal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public static boolean unirPdf(String file1, String file2, String salida){

        Document document = new Document();
        
        FileInputStream archivo1;
        try {
            archivo1 = new FileInputStream(new File(file1));
            FileInputStream archivo2 = new FileInputStream(new File(file2));        
            FileOutputStream outputStream = new FileOutputStream(new File(salida));


            PdfWriter writer = PdfWriter.getInstance(document, outputStream);
            document.open();
            PdfContentByte cb = writer.getDirectContent();

            PdfReader reader1 = new PdfReader(archivo1);
            for (int i = 1; i <= reader1.getNumberOfPages(); i++) {
                document.newPage();
                PdfImportedPage page = writer.getImportedPage(reader1, i);
                cb.addTemplate(page, 0, 0);
            }

            PdfReader reader2 = new PdfReader(archivo2);
            for (int i = 1; i <= reader2.getNumberOfPages(); i++) {
                document.newPage();
                PdfImportedPage page = writer.getImportedPage(reader2, i);
                cb.addTemplate(page, 0, 0);
            }

            outputStream.flush();
            document.close();
            outputStream.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(IuPpal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DocumentException ex) {
            Logger.getLogger(IuPpal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(IuPpal.class.getName()).log(Level.SEVERE, null, ex);
        }

        return true;
    }
}
